version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nombre-de-tu-imagen
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tu-contraseña-root
      MYSQL_DATABASE: tu-base-de-datos
      MYSQL_USER: tu-usuario
      MYSQL_PASSWORD: tu-contraseña
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
