name: Laravel CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt update && sudo apt install -y openssh-client

      - name: Run PHP Artisan commands
        run: |
          ssh -tt root@http://192.168.1.210 "docker exec -it medical-system-apache bash -c 'cd /path/to/your/laravel && \
          composer install --no-progress --no-suggest --no-interaction && \
          composer update --no-progress --no-suggest --no-interaction && \
          php artisan cache:clear && \
          php artisan view:clear && \
          php artisan config:clear && \
          chmod -R 777 storage bootstrap/cache && \
          php artisan optimize:clear && \
          php artisan migrate --force --no-interaction'"
